spring.application.name=tcg.decklists.api
spring.liquibase.enabled=true
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:testing1234}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tcg_decklists}
spring.datasource.driver-class-name=org.postgresql.Driver
